### ISSUE TITLE
Use Alien module to install tidy

### ISSUE THREAD

**Issue by robrwo** [petdance/html-tidy5#8]
I have started working on an Alien::TidyHTML5 module at https://github.com/robrwo/Alien-TidyHTML5 to install libtidy. If/when it is done and released, HTML::Tidy5 should require this.

**Comment by petdance** [comment]
If/when it is done and released, let's discuss.  Thanks.

**Comment by robrwo** [comment]
First version released https://metacpan.org/release/Alien-TidyHTML5

**Comment by petdance** [comment]
What do I need to add to use it?  How do I use it?  HTML::Tidy uses Alien::Tidyp.  Have things changed in the Alien:: world since then, or should I just adapt what's in HTML::Tidy?

**Comment by robrwo** [comment]
It's my first Alien module, so I can't tell you how things have changed. But it seems pretty easy:
```diff
diff --git a/Makefile.PL b/Makefile.PL
index d2908b1..a3f94a8 100644
--- a/Makefile.PL
+++ b/Makefile.PL
@@ -8,9 +8,7 @@ use warnings;
 use ExtUtils::MakeMaker 6.48;
 use ExtUtils::Liblist;
 use Config;
-
-my $libs = $^O eq 'freebsd' ? '-ltidy5' : '-ltidy';
-my $inc = "-I. -I/usr/include/tidy -I/usr/local/include/tidy -I$Config{usrinc}/tidy";
+use Alien::Base::Wrapper qw/ Alien::TidyHTML5 !export /;
 
 if ( not eval { require LWP::Simple; 1; } ) {
     print <<'EOF';
@@ -48,9 +46,11 @@ my $parms = {
         },
     },
 
-    LIBS                => [$libs],
-    NEEDS_LINKING       => 1,
-    INC                 => $inc,
+    CONFIGURE_REQUIRES => {
+        'Alien::Base::Wrapper' => '0',
+        'Alien::TidyHTML5'     => '0',
+    },
+    Alien::Base::Wrapper->mm_args,
 
     EXE_FILES           => [qw(bin/webtidy5)],
     dist                => { COMPRESS => 'gzip -9f', SUFFIX => 'gz', },
```

See [Alien::Build::Manual::AlienUser](https://metacpan.org/pod/Alien::Build::Manual::AlienUser).

**Comment by petdance** [comment]
I would be glad to incorporate this if we could get it so that Alien::Tidy5 was optional for those people who don't need it because they already have Tidy installed.
